import json
import os
import re
import subprocess
import numpy as np

from .blo import BLO


class Watwa(BLO):
    """
    Bilevel problem wrapper for the WatwaOS optimizer.

    Leader:   selects a configuration decision for each switch point.
              x ∈ {0, 1, 2}^s  where s = number of configuration switch points.

              Each position encodes:
                0 = no frequency change
                1 = switch to low frequency
                2 = switch to high frequency

              Total scenarios = 3^s (grows exponentially with s).
              Each UART/IO loop contributes 2 switch points → s = 2 * num_io_loops.

    Follower: WatwaOS ILP solver finds the optimal energy configuration
              for the program under the leader's chosen scenario.
              Returns total energy consumption as the objective value.

    Two modes:
      - Online mode:  WatwaOS is available → runs make pipeline to generate data
      - Offline mode: pre-generated JSON + PML files exist → loads directly
                      Use this mode for training on a separate machine (e.g. GPU workstation)
    """

    def __init__(self):
        pass


    # ------------------------------------------------------------------
    # Instance handling
    # ------------------------------------------------------------------

    def sample_instance(self, cfg, scale=True):
        """
        Sample a random program instance from the pool defined in cfg.

        cfg.program_dirs : list of paths to program directories,
                           each containing a Makefile and src/app.c
        """
        program_dir = np.random.choice(cfg.program_dirs)
        instance = self.read_instance(cfg, program_dir, scale=scale)
        return instance


    def read_instance(self, cfg, program_dir, scale=True):
        """
        Read a program instance and return scenario data.

        Offline mode (default for training on GPU workstation):
          Loads pre-generated build/optimize-result.json and build/app.c.pml.
          No WatwaOS or LLVM toolchain required.

        Online mode (requires WatwaOS + LLVM on VM):
          Runs make clean → make build → make optimize to generate data first.

        Directory structure expected:
            program_dir/
                src/app.c
                Makefile
                build/
                    optimize-result.json   ← generated by make optimize
                    app.c.pml              ← generated by make build
                    scenarios/
                        gurobi-model-*.lp  ← generated by make optimize

        Returns dict with:
            program_dir    : path to program directory
            scenarios      : dict {scenario_key: {time, energy, energy_scaled}}
            ideal_energy   : optimal energy found by exhaustive ILP
            ideal_scenario : key of the optimal scenario e.g. "(2, 0)"
            worst_energy   : max energy across all scenarios
            k              : number of switch points
        """
        result_path = os.path.join(program_dir, "build", "optimize-result.json")
        pml_path    = os.path.join(program_dir, "build", "app.c.pml")

        if os.path.exists(result_path) and os.path.exists(pml_path):
            # --- Offline mode: load pre-generated data ---
            with open(result_path) as f:
                result = json.load(f)
        else:
            # --- Online mode: run WatwaOS pipeline ---
            result = self._run_watwa(program_dir)

        scenarios      = result["solutions"]
        ideal_energy   = result["ideal_energy"]
        ideal_scenario = result["ideal_scenario"]

        # Infer k from first scenario key e.g. "(2, 0)" -> k=2
        first_key = next(iter(scenarios))
        k = len(eval(first_key))

        # Normalize energy by worst-case scenario
        worst_energy = max(s["energy"] for s in scenarios.values())
        for s in scenarios.values():
            s["energy_scaled"] = s["energy"] / worst_energy if worst_energy > 0 else 0.0

        if not scale:
            worst_energy = 1.0
            for s in scenarios.values():
                s["energy_scaled"] = s["energy"]

        instance = {
            "program_dir"    : program_dir,
            "scenarios"      : scenarios,
            "ideal_energy"   : ideal_energy,
            "ideal_scenario" : ideal_scenario,
            "worst_energy"   : worst_energy,
            "k"              : k,
        }

        return instance


    # ------------------------------------------------------------------
    # Follower
    # ------------------------------------------------------------------

    def solve_follower(self, instance, x):
        """
        Solve the follower problem for a given leader decision x.

        x is a categorical vector of length k with values in {0, 1, 2},
        e.g. [2, 0] corresponds to scenario key "(2, 0)".

        Since WatwaOS pre-computes all scenarios exhaustively, we look
        up the result directly from the cached scenario dict.

        Parameters
        ----------
        instance : dict    output of read_instance()
        x        : list    categorical vector of length k, values in {0,1,2}

        Returns
        -------
        dict with follower_obj, follower_sol, leader_obj, leader_sol
        """
        scenario_key = self._x_to_scenario_key(x)
        scenarios    = instance["scenarios"]

        if scenario_key not in scenarios:
            raise KeyError(
                f"Scenario {scenario_key} not found in pre-computed results."
            )

        energy = scenarios[scenario_key]["energy_scaled"]

        res = {
            "follower_obj" : energy,
            "follower_sol" : list(x),
            "leader_obj"   : energy,
            "leader_sol"   : list(x),
        }

        return res


    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _run_watwa(self, program_dir):
        """
        Run the full WatwaOS pipeline for a program directory.

        Only called in online mode when pre-generated data is not available.
        Requires WatwaOS + LLVM toolchain on the current machine.

        Steps:
            1. make clean
            2. make build      -> compiles app.c to app.o, app.o.ll, app.c.pml
            3. make optimize   -> runs optimizer.py -> optimize-result.json
        """
        result_path = os.path.join(program_dir, "build", "optimize-result.json")

        self._make(program_dir, "clean")
        self._make(program_dir, "build")
        self._make(program_dir, "optimize")

        if not os.path.exists(result_path):
            raise FileNotFoundError(
                f"optimize-result.json not found at {result_path}"
            )

        with open(result_path) as f:
            output = json.load(f)

        return output


    def _make(self, program_dir, target):
        """Run a make target in the given program directory."""
        result = subprocess.run(
            ["make", target],
            cwd=program_dir,
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"make {target} failed in {program_dir}:\n{result.stderr}"
            )


    def _x_to_scenario_key(self, x):
        """
        Convert categorical leader decision vector x to a scenario lookup key.

        x = [2, 0]        →  "(2, 0)"
        x = [1, 2, 0, 1]  →  "(1, 2, 0, 1)"

        Matches the key format in optimize-result.json exactly.
        """
        return str(tuple(int(v) for v in x))